#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Будь ласка, запустіть цей скрипт з правами root."
  exit 1
fi

echo "Починаємо встановлення Zabbix..."

apt update -y && apt upgrade -y

apt install -y wget gnupg2 software-properties-common

wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3%2Bubuntu20.04_all.deb
dpkg -i zabbix-release_6.0-3+ubuntu20.04_all.deb
apt update -y

apt install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-agent

apt install -y mysql-server

echo "Налаштування бази даних для Zabbix..."
mysql -uroot -e "CREATE DATABASE zabbix CHARACTER SET utf8 COLLATE utf8_bin;"
mysql -uroot -e "CREATE USER 'zabbix'@'localhost' IDENTIFIED BY 'password';"
mysql -uroot -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';"
mysql -uroot -e "FLUSH PRIVILEGES;"

echo "Імпорт початкової структури бази даних..."
zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p'password' zabbix

echo "Налаштування конфігураційного файлу Zabbix..."
sed -i "s/# DBPassword=/DBPassword=password/" /etc/zabbix/zabbix_server.conf

echo "Запуск та увімкнення сервісів..."
systemctl restart zabbix-server zabbix-agent apache2
systemctl enable zabbix-server zabbix-agent apache2

echo "Встановлення Zabbix завершено! Відкрийте веб-інтерфейс: http://<your_server_ip>/zabbix"

exit 0
